### ISSUE TITLE
Punctuation on bullet point lists is inconsistent 

### ISSUE THREAD

**Issue by sgreene570** [ComputerScienceHouse/Constitution#110]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [X] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Some bullet lists have periods at the end of every list item, some do not.  This is very minor, but could probably be scripted and fixed quickly.

**Comment by gambogi** [comment]
I believe this was fixed by #113
