### ISSUE TITLE
Vague wording in Active Member section.

### ISSUE THREAD

**Issue by jeid64** [ComputerScienceHouse/Constitution#13]
https://github.com/ComputerScienceHouse/Constitution/blob/master/articles.tex#L141

Receive priority over whom?
Also, are only active members on co-op allowed to come back on floor? Does that mean Harlan needs to pay dues to become an active member in order to be able to move on floor, meaning they pay dues for when they are not here?

Also, we don't define anywhere that an alum in good standing can just pay dues and become an active member again. We actually never define what an alum in good standing is. We only say how you become one.

Grammar error. https://github.com/ComputerScienceHouse/Constitution/blob/master/articles.tex#L168 Are not subject "to" any evaluations.

**Comment by gambogi** [comment]
Typo resolved. Closing.
