### ISSUE TITLE
Full semester is not defined

### ISSUE THREAD

**Issue by mxmeinhold** [ComputerScienceHouse/Constitution#155]
https://github.com/ComputerScienceHouse/Constitution/blob/3c28d9535f982426275e921b17e790424a48b907/articles.tex#L451
https://github.com/ComputerScienceHouse/Constitution/blob/3c28d9535f982426275e921b17e790424a48b907/articles.tex#L457

A full semester as referred to here is not defined, and could be taken to mean either a contiguous RIT semester or 16 weeks in total.

**Comment by esoccoli** [comment]
Resolved by #232 with the removal of this line. We discovered that this line is not enforcable because RIT policy requires that all active members of clubs on campus must be able to run for and hold eboard positions
