### ISSUE TITLE
Define amount of freshmen rooms

### ISSUE THREAD

**Issue by rdausilio** [ComputerScienceHouse/Constitution#159]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

Housing board/selections thing - How many freshmen rooms should be reserved for next year 33%.

**Comment by rdausilio** [comment]
Clarifying - minimum 33%

**Comment by VictoriaWeaver** [comment]
Please don't hard code in a number.  This is something RIT dictates, so if they decide to change it every year, you need an amendment every year.  Please put something along the lines of "house shall adhere to the guidelines of room assignments set forth by RIT".  That way you can just ask the advise what it is, or document the history of what the % is over time on the wiki or something.
