### ISSUE TITLE
Update number of on-floors + recalculate yearly budget

### ISSUE THREAD

**Issue by BootSkiing** [ComputerScienceHouse/Constitution#189]
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:

Since dropping Fish from on-floor housing, the max number of on-floor members has dropped from 72 to 55. This should be reflected in section 5.D.1.C "Breakdown of Dues for Directorship Budgets" where the new suggested total budget should be $8800.

We used this budget number for 2019/20, but the change was never reflected constitutionally.

**Comment by esoccoli** [comment]
Resolved by #232
