### ISSUE TITLE
No explicit vote defined for introductory members

### ISSUE THREAD

**Issue by ajgajg1134** [ComputerScienceHouse/Constitution#27]
See bylaws 4.B.1 sub section c. There is no explicit wording stating that the vote ought to be a simple majority as it is currently done.

**Comment by gambogi** [comment]
This seems reasonable, why not make a PR and news post for an amendment?

**Comment by devinmatte** [comment]
I noticed that this amendment was never written. I've written it up and will be submitting a pull request.
