### ISSUE TITLE
Problems with terms of membership?

### ISSUE THREAD

**Issue by jeid64** [ComputerScienceHouse/Constitution#52]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Reading over the terms of membership and eboard, seems there are two weird inconsistencies.
https://github.com/ComputerScienceHouse/Constitution/blob/master/articles.tex#L512

> The term of an officer will be abbreviated due to resignation, impeachment, failure of the evaluation process, or change in membership status.

Does failing Spring Evals end the term of the officer? Current practice has been that they keep the position until the end of the year, regardless of Spring Evals. 
Then there is a contradiction here, I think. 
https://github.com/ComputerScienceHouse/Constitution/blob/master/articles.tex#L200

> Active Membership shall last until the member: resigns, fails the Evaluation Process, or changes membership status.

Contradicts here:

https://github.com/ComputerScienceHouse/Constitution/blob/master/bylaws.tex#L296

> If the member has previously passed an Membership Evaluation they will move to Alumni Membership status at the end of the Standard Operating Session (\ref{Alumni Membership Selection}).

Your active membership term ends if you "fail the Evaluation Process." But, you move to Alumni Membership at the end of the semester. So, do you still get to vote?

**Comment by ajgajg1134** [comment]
> Your active membership term ends if you "fail the Evaluation Process." But, you move to Alumni Membership at the end of the semester. So, do you still get to vote?

Specifically you only move to alumni in good standing at the end of the year after passing, so this specific part isn't a contradiction. But the rest definitely could be more clear.

**Comment by gambogi** [comment]
@jeid64 I think the appropriate fix here is to remove the "failure of the evaluation process" in the eboard description, and "fails the evaluation process" from active membership. That way the transition timing is specified only in the bylaws description of the evaluations process, and the eboard term reflects what actually happens.

**Comment by saucetray** [comment]
This can be marked as resolved.
