### ISSUE TITLE
Grammar problem.

### ISSUE THREAD

**Issue by jeid64** [ComputerScienceHouse/Constitution#54]
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [X] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
What are articles?
https://github.com/ComputerScienceHouse/Constitution/blob/master/bylaws.tex#L296
"If the member has previously passed an Membership Evaluation they will move to Alumni Membership status at the end of the Standard Operating Session (\ref{Alumni Membership Selection})."

Change an to a.

**Comment by gambogi** [comment]
![image](https://cloud.githubusercontent.com/assets/1028704/14690153/a9e49cf0-0718-11e6-8d89-3d5edede69a9.png)
Awaiting your PR
