### ISSUE TITLE
Establish CI

### ISSUE THREAD

**Issue by gambogi** [ComputerScienceHouse/Constitution#57]
Summary of issue:
We really really really should not track changes in the pdf blob.

**Comment by harlanhaskins** [comment]
ShareLaTeX has a 'cloud compiler' that automatically recompiles changes per commit.

**Comment by mbillow** [comment]
The problem here is compiling process of our constitution, since both documents contain references to each other. I have found countless solutions I would love to set-up but none of them can handle the way we have to compile the documents. If we combined them into one (which I would love and would make searching infinitely easier), you could consider this problem solved.

**Comment by liam-middlebrook** [comment]
I think that using TravisCI would be a good solution for this, the only complication being where the constitution is stored after being compiled. We could write a script to run on san that would allow files to be PUT if a certain key was sent with them. I'm going to contact TravisCI support and see if we can get an organization-wide educational account with the premium features.

**Comment by mbillow** [comment]
Just have Travis dump them somewhere on Filer and then symlink it to a directory on San over NFS. That way we don't have to wait for / trigger scripts.

**Comment by gambogi** [comment]
Then you have a world writable file that people frequently download and open.

**Comment by gambogi** [comment]
We could also just set up a cron job that runs the makefile every night or something. Doesn't need to be too fancy.

**Comment by sman591** [comment]
Just have the CI commit the updated PDF?

**Comment by liam-middlebrook** [comment]
I don't see why we would want to store them on filer either way. There's no good reason to have it dependent on NFS.

**Comment by liam-middlebrook** [comment]
@sman591 I'd rather keep the binary PDF blobs out of Git in general.

**Comment by mbillow** [comment]
Why would the file be world writable? Also, you aren't going to want to run Travis on San (that's not the point of that box). So if you want it to be served from csh.rit.edu, you are going to need it on San. NFS is probably the most reliable way to do that.

**Comment by liam-middlebrook** [comment]
TravisCI works by hooking into the Git hooks that are exposed by GitHub. Upon a new pull request or regular commit TravisCI will trigger a build event where it will compile the constitution. 

After the constitution is compiled we need a place to put the PDFs. There's no reason why we can't just drop two PDF files directly on san in somewhere like `/var/www/pub/constitution` as opposed to droppign them on filer.

**Comment by mbillow** [comment]
Where are you running Travis though? It shouldn't be on San and if you aren't going to have some weird syncing cron job, than it makes the most sense to transfer them over NFS. We can move the implementation discussion to Bored Room, it doesn't need to be here.

**Comment by liam-middlebrook** [comment]
TravisCI is a hosted service, we don't run it locally.

**Comment by mbillow** [comment]
I was under the impression that we were going to host it locally.

**Comment by dgonyeo** [comment]
TravisCI isn't something you can host yourself unless you want to pay a lot of money.

**Comment by WillDignazio** [comment]
Can we first elaborate on what problem there is with including the binary?

Our PDF's are relatively small, and while there is a consistency issue, we can trivially solve this with a commit hook for push (as opposed to a maintained server hook). 

Binary diffs of this size should be no problem (tm).

**Comment by gambogi** [comment]
@WillDignazio They cause unnecessary merge conflicts every time

**Comment by dgonyeo** [comment]
Could we just have a cron job somewhere do a `git pull && make && rsync *.pdf san.csh.rit.edu:/var/www/priv/constitution/` every midnight, and just not include the PDF on github?

(obviously this requires creating that virtualhost)

**Comment by WillDignazio** [comment]
There are github commit hooks that can inform us when to do the rebuild, but imo, it's way overkill.

**Comment by gambogi** [comment]
@ComputerScienceHouse/root-type-people Yo can we get that one liner in cron going?

**Comment by mbillow** [comment]
https://constitution.csh.rit.edu/articles.pdf
https://constitution.csh.rit.edu/bylaws.pdf

Enjoy your up to date (every 12 hours [0:00 & 12:00]) constitution. 
Warning: Give the CNAME time to propagate or use CSH's DNS servers.

**Comment by liam-middlebrook** [comment]
:shipit:
