### ISSUE TITLE
We need docs

### ISSUE THREAD

**Issue by ajgajg1134** [ComputerScienceHouse/Constitution#63]
The constitution is one of those documents that should be easy for a freshman walking in to CSH during the first week to make a PR to with very little git or unix experience. We should add instructions in the README or create a CONTRIBUTING.md that simply adds some info like that you need to modify the .tex files first, you must have pdflatex installed and then you must run make twice before committing and making a PR. Something like that would really lower the barrier for people to help with the constitution.

**Comment by liam-middlebrook** [comment]
Fixed in c00f024a782bfe8cc2c103dcf35446d541ae3a93
