### ISSUE TITLE
Advisory membership process appears to just be weird.

### ISSUE THREAD

**Issue by jeid64** [ComputerScienceHouse/Constitution#7]
In the bylaws this section pops up.
d. Ballots will then be distributed for a secret ballot, fifty-percent House vote, as defined in 5.C.2. If more than two advisors are selected via this process, the Executive Board may call for a revote amongst the candidates selected in order to reduce the number of advisors to a workable level. If this decision is made, the candidates selected in the first ballot become the nominees for the second ballot and Step Three and Four are repeated. This recast process may not be repeated a second time.

This section is "numbered" by letter and references a three and four, which do not exist. 

Also, it should probably be changed to say "as defined in the Constitution in 5.C.2" as that is talked about in the constitution not in the bylaws. Also, if you wanted to shorten that, you could define something like B.5.C.2 as bylaws section 5.C.2 and C.5.C.2 as constitution section 5.C.2. Just a thought.

**Comment by liam-middlebrook** [comment]
This seems to be acknowledged by #51

**Comment by mbillow** [comment]
Addressed by #51.
